# Generated by Django 3.0.5 on 2020-04-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='currentHp',
            new_name='current_hp',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='maxHp',
            new_name='max_hp',
        ),
    ]
