# Generated by Django 3.0.5 on 2020-05-15 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0002_auto_20200515_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='world.Base')),
            ],
        ),
    ]
