# Generated by Django 3.0.5 on 2020-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveslot',
            name='save_name',
            field=models.CharField(default='save 1', max_length=255),
            preserve_default=False,
        ),
    ]
