# Generated by Django 3.0.5 on 2020-05-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20200515_1440'),
        ('game', '0002_saveslot_save_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveslot',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_slot', to='world.Base'),
        ),
    ]
